version: '3'
services:
  starlette:
    container_name: paaster_backend
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      paaster_max_paste_size: 1049000
      paaster_max_iv_size: 42
      paaster_open_api: '{"title": "paaster.io", "version": "2.0.0"}'
      paaster_mongo: '{"host": "paaster_mongodb", "port": 27017, "collection": "paasterv2"}'
      paaster_s3: '{"endpoint_url": "","secret_access_key": "","access_key_id": "","region_name": "","bucket": "","folder": "pastes","download_url": ""}'
      paaster_proxy_urls: '{"frontend": "http://localhost:8889", "backend": "http://localhost:8888"}'
    depends_on:
      - mongodb
    networks:
      - backend

  vite:
    container_name: paaster_frontend
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
      args:
        # Proxied backend URL, NO TRAILING SLASH!
        VITE_API_URL: "http://localhost:8888"
        # Name what appears on the website.
        VITE_NAME: "paaster"
    restart: unless-stopped
    ports:
      - "8889:80"

  mongodb:
    image: mongo
    container_name: paaster_mongodb
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
