version: '3'
services:
  starlette:
    build:
      dockerfile: ./Dockerfile
      context: ./paaster-backend
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      MONGO_IP: "mongodb"
      MONGO_PORT: 27017
      MONGO_DB: "paaster"
      NANO_ID_LEN: 21
      READ_CHUNK: 1024
    volumes:
      # If a non external 'SAVE_PATH' used this should be ensured that it isn't deleted
      - appdata:/app/pastes
    depends_on:
      - mongodb
    networks:
      - backend

  vite:
    build:
      dockerfile: ./Dockerfile
      context: ./paaster-frontend
      args:
        # Proxied host URL, NO TRAILING SLASH!
        VITE_BACKEND: "http://localhost:8888"
        VITE_NAME: "paaster"
    restart: unless-stopped
    ports:
      - "8889:80"

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
