version: '3'
services:
  starlette:
    build:
      dockerfile: ./Dockerfile
      context: ./paaster-backend
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      MONGO_IP: "mongodb"
      MONGO_PORT: 27017
      MONGO_DB: "paaster"
      NANO_ID_LEN: 21
      READ_CHUNK: 1024
      # This is the max paste size of the encrypted data.
      MAX_PASTE_SIZE_MB: 3
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      # Proxied Frontend URL.
      FRONTEND_PROXIED: ""
    volumes:
      # If a non external 'SAVE_PATH' used this should be ensured that it isn't deleted
      - appdata:/app/pastes
    depends_on:
      - mongodb
    networks:
      - backend

  vite:
    build:
      dockerfile: ./Dockerfile
      context: ./paaster-frontend
      args:
        # Proxied backend URL, NO TRAILING SLASH!
        VITE_BACKEND: "http://localhost:8888"
        VITE_NAME: "paaster"
    restart: unless-stopped
    ports:
      - "8889:80"

  redis:
    container_name: redis
    image: redis
    volumes: 
      - redis:/data
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis:
    driver: local
  mongodbdata:
    driver: local
  appdata:
    driver: local
