version: '3'
services:
  starlette:
    container_name: paaster_starlette
    build:
      dockerfile: ./Dockerfile
      context: ./paaster-backend
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      MONGO_IP: "paaster_mongodb"
      MONGO_PORT: 27017
      MONGO_DB: "paaster"
      # Nano ID length https://zelark.github.io/nano-id-cc/
      NANO_ID_LEN: 21
      # Chunk size when sending a encrypted paste back to the client.
      READ_CHUNK: 1024
      # This is the max paste size of the encrypted data.
      MAX_PASTE_SIZE_MB: 3
      REDIS_HOST: "paaster_redis"
      REDIS_PORT: 6379
      # Proxied Frontend URL.
      FRONTEND_PROXIED: "http://localhost:8889"
    volumes:
      # If you change 'SAVE_PATH' this needs to be changed,
      # changing 'SAVE_PATH' is not recommended.
      - appdata:/app/pastes
    depends_on:
      - mongodb
    networks:
      - backend

  vite:
    container_name: paaster_frontend
    build:
      dockerfile: ./Dockerfile
      context: ./paaster-frontend
      args:
        # Proxied backend URL, NO TRAILING SLASH!
        VITE_BACKEND: "http://localhost:8888"
        # Name what appears on the website.
        VITE_NAME: "paaster"
    restart: unless-stopped
    ports:
      - "8889:80"

  redis:
    container_name: paaster_redis
    image: redis
    volumes: 
      - redis:/data
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: paaster_mongodb
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis:
    driver: local
  mongodbdata:
    driver: local
  appdata:
    driver: rclone
    driver_opts:
      remote: "backblaze:xxx"
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
