[tool.poetry]
name = "paaster"
version = "2.0.0"
description = ""
authors = ["WardPearce <wardpearce@protonmail.com>"]
packages = [
    {include = "*", from = "app"},
    {include = "run.py"}
]

[tool.poetry.scripts]
server = "run:main"

[tool.poetry.dependencies]
python = "^3.10"
motor = "^3.5.0"
bcrypt = "^4.1.3"
aiobotocore = "^2.13.1"
nanoid = "^2.0.0"
argon2-cffi = "^23.1.0"
types-aiobotocore-s3 = "^2.13.1"
pydantic = "^2.8.2"
pydantic-settings = "^2.3.4"
uvicorn = "^0.30.3"
litestar = "^2.9.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.1"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
mypy = "^1.11.0"
types-aiobotocore = "^2.13.1"
motor-types = "^1.0.0b4"
pytest-asyncio = "^0.23.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
