[tool.poetry]
name = "paaster"
version = "2.0.0"
description = ""
authors = ["WardPearce <wardpearce@protonmail.com>"]
packages = [
    {include = "*", from = "app"},
    {include = "run.py"}
]

[tool.poetry.scripts]
server = "run:main"

[tool.poetry.dependencies]
python = "^3.10"
motor = "^3.4.0"
bcrypt = "^4.1.2"
aiobotocore = "^2.12.3"
nanoid = "^2.0.0"
argon2-cffi = "^23.1.0"
litestar = {extras = ["full"], version = "^2.8.0"}
types-aiobotocore-s3 = "^2.12.3"
pydantic = "^2.6.4"
pydantic-settings = "^2.2.1"
uvicorn = "^0.29.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
mypy = "^1.9.0"
types-aiobotocore = "^2.12.3"
motor-types = "^1.0.0b4"
pytest-asyncio = "^0.23.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
