[tool.poetry]
name = "paaster"
version = "2.0.0"
description = ""
authors = ["WardPearce <wardpearce@protonmail.com>"]
readme = "README.md"
packages = [
    {include = "*", from = "app"},
    {include = "run.py"}
]

[tool.poetry.scripts]
server = "run:main"

[tool.poetry.dependencies]
python = "^3.10"
starlite = {extras = ["full"], version = "^1.51.0"}
motor = "^3.1.1"
bcrypt = "^4.0.1"
aiobotocore = "^2.4.2"
nanoid = "^2.0.0"
uvicorn = "^0.20.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
