[tool.poetry]
name = "paaster"
version = "2.0.0"
description = ""
authors = ["WardPearce <wardpearce@protonmail.com>"]
packages = [
    {include = "*", from = "app"},
    {include = "run.py"}
]

[tool.poetry.scripts]
server = "run:main"

[tool.poetry.dependencies]
python = "^3.10"
motor = "^3.4.0"
bcrypt = "^4.1.3"
aiobotocore = "^2.13.0"
nanoid = "^2.0.0"
argon2-cffi = "^23.1.0"
types-aiobotocore-s3 = "^2.13.0"
pydantic = "^2.7.4"
pydantic-settings = "^2.3.3"
uvicorn = "^0.30.1"
litestar = "^2.9.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
mypy = "^1.10.0"
types-aiobotocore = "^2.13.0"
motor-types = "^1.0.0b4"
pytest-asyncio = "^0.23.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
