name: Production Vite workflow

on:
  push:
    branches:
    - Production

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./paaster-frontend

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: npm install
      - name: Check codebase
        run: npm run check
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: wardpearce/paaster-frontend:latest
